---
# restore-or-toggle-apt-proxy.yml
- hosts: all
  become: true
  vars:
    apt_proxy_enabled: true          # <-- set to false to disable again
    apt_http_proxy:  "http://proxy.example.com:3128"
    apt_https_proxy: "http://proxy.example.com:3128"
    # Domains/IPs that should bypass the proxy (optional)
    apt_no_proxy: ["localhost", "127.0.0.1", "169.254.169.254", ".example.internal"]

  tasks:
    - name: Remove the "force no proxy" file if present
      file:
        path: /etc/apt/apt.conf.d/99no-proxy
        state: absent

    - name: Ensure APT proxy file is present when enabled
      copy:
        dest: /etc/apt/apt.conf.d/01proxy
        mode: '0644'
        content: |
          Acquire::http::Proxy  "{{ apt_http_proxy }}";
          Acquire::https::Proxy "{{ apt_https_proxy }}";
          {% for host in apt_no_proxy | default([]) %}
          Acquire::http::Proxy::"{{ host }}"  "DIRECT";
          Acquire::https::Proxy::"{{ host }}" "DIRECT";
          {% endfor %}
      when: apt_proxy_enabled
      notify: apt update cache

    - name: Remove APT proxy file when disabled
      file:
        path: /etc/apt/apt.conf.d/01proxy
        state: absent
      when: not apt_proxy_enabled
      notify: apt update cache

    - name: Ensure proxy env vars exist in /etc/environment when enabled
      lineinfile:
        path: /etc/environment
        create: yes
        state: present
        regexp: '^{{ item.key }}='
        line: '{{ item.key }}="{{ item.val }}"'
      loop:
        - { key: http_proxy,  val: '{{ apt_http_proxy }}' }
        - { key: https_proxy, val: '{{ apt_https_proxy }}' }
        - { key: no_proxy,    val: '{{ (apt_no_proxy | default([])) | join(",") }}' }
        - { key: HTTP_PROXY,  val: '{{ apt_http_proxy }}' }
        - { key: HTTPS_PROXY, val: '{{ apt_https_proxy }}' }
        - { key: NO_PROXY,    val: '{{ (apt_no_proxy | default([])) | join(",") }}' }
      when: apt_proxy_enabled

    - name: Remove proxy env vars from /etc/environment when disabled
      lineinfile:
        path: /etc/environment
        regexp: '^(http_proxy|https_proxy|no_proxy|HTTP_PROXY|HTTPS_PROXY|NO_PROXY)='
        state: absent
      when: not apt_proxy_enabled

  handlers:
    - name: apt update cache
      apt:
        update_cache: yes

