---
# update-upgrade-minimal.yml
- name: Minimal package updates (no proxy tweaks)
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    # Debian/Ubuntu: apt update && apt upgrade
    - name: Apt | Update package cache
      apt:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Apt | Upgrade packages (no dist-upgrade)
      apt:
        upgrade: yes          # == apt-get upgrade
      when: ansible_facts['os_family'] == 'Debian'

    # RHEL/Fedora/CentOS: update all packages to latest
    - name: DNF | Upgrade packages
      dnf:
        name: "*"
        state: latest
      when: ansible_facts['pkg_mgr'] == 'dnf'

    - name: YUM | Upgrade packages (legacy)
      yum:
        name: "*"
        state: latest
      when: ansible_facts['pkg_mgr'] == 'yum'
